#define	NeXT	1
#define HW_AST 1
#define MACH_ASSERT 0
#define MACH_COMPAT 1
#define MACH_DEBUG 1
#define MACH_FASTLINK 0
#define MACH_FIXPRI 1
#define MACH_HOST 0
#define MACH_IPC_SIGHACK 0
#define MACH_IPC_STATS 0
#define MACH_IPC_TCACHE 0
#define MACH_IPC_WWA 0
#define MACH_IPC_XXXHACK 0
#define MACH_KDB 0
#define MACH_LDEBUG 0
#define MACH_LOAD 0
#define MACH_NBC 1
#define MACH_NET 1
#define MACH_NP 0
#define MACH_OLD_VM_COPY 1
#define MACH_PAGEMAP 0
#define MACH_SCTIMES 0
#define MACH_XP 0
#define MACH_XP_FPD 0
#define NCPUS 1
#define SIMPLE_CLOCK 1
#define STAT_TIME 1
#define SUN_LOCK 0
#define SUN_NFS 1
#define SUN_RPC 1
#define SUN_VFS 1
