# 
# Mach Operating System
# Copyright (c) 1987 Carnegie-Mellon University
# All rights reserved.  The CMU software License Agreement specifies
# the terms and conditions for use and redistribution.
#
######################################################################
# HISTORY
# 09-May-87  Mike Accetta (mja) at Carnegie-Mellon University
#	Created (for archiving).
#	[ V5.1(XF11) ]
#
######################################################################
#


#  Display any newly modified files

NEWSRC=.

NEWSRC: ${NEWSRC}

${NEWSRC}: Makefile *.[ch]
	@echo $?
